version: '3'

services:
  db:
    container_name: cafe_order_db
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: showmethemoney
      MYSQL_DATABASE: cafe
      LANG: C.UTF-8
      TZ: Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci